// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFwQr3K0B5LI6_VF3WlbHEix1iCzyqBRI',
    appId: '1:899344793859:android:a1819a7b71ef017b4de936',
    messagingSenderId: '899344793859',
    projectId: 'fir-1-45e9b',
    databaseURL: 'https://fir-1-45e9b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-1-45e9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC97TT5ydjNxvTJmNUCaqTQdHvePwGtJv0',
    appId: '1:899344793859:ios:0f335cf5525aae064de936',
    messagingSenderId: '899344793859',
    projectId: 'fir-1-45e9b',
    databaseURL: 'https://fir-1-45e9b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-1-45e9b.firebasestorage.app',
    iosBundleId: 'com.example.huanmaiw',
  );
}
